### ISSUE TITLE
`main` variable becomes function call

### ISSUE THREAD

**Issue by urlsangel** [akmiller01/IATI-Reference-Generator#1]
Hi @akmiller01 

How come the `main` variable becomes a function call on this line?

https://github.com/akmiller01/IATI-Reference-Generator/blob/cb29eee3410a3a3895800967316d5c4474734a32/extract_html.py#L47

```
for tag in main():
```

**Comment by akmiller01** [comment]
Got the syntax from here: https://stackoverflow.com/a/39223223

Evidently BeautifulSoup nodes are functions, and they return an iterator of all subsequent nodes.

**Comment by urlsangel** [comment]
Nice! Hadn't seen that before 👍 😀

Sorry for opening an issue, was the easiest way to discuss that line in particular!
